# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wabt
      run: brew install wabt
    - name: Prepare for spec
      run: ./Spec/build.sh
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
